---
title: "Игровой тур"
author: "Памятка судьям"
date: "Тур 5"
output:
  pdf_document:
    toc: false
    toc_depth: 2
    keep_tex: yes
    number_sections: false
    fig_width: 4
    fig_height: 3
    fig_caption: true
    highlight: tango
    latex_engine: xelatex
  word_document: default
  html_document: default
lang: ru-RU
mainfont: Linux Libertine O
fontsize: 10pt
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
documentclass: article
linkcolor: blue
urlcolor: blue
citecolor: blue
header-includes:
- \newfontfamily{\cyrillicfonttt}{Linux Libertine O}
- \newfontfamily{\cyrillicfont}{Linux Libertine O}
- \newfontfamily{\cyrillicfontsf}{Linux Libertine O}
editor_options: 
  chunk_output_type: console
---

## Регламент тура

### Первый этап, индивидуальный

* 10 минут первый этап. 
* Игроки играют пара на пару на поле $1 \times 5$. 
* Сажаем игроков команды друг напротив друга.
* В каждой паре играющих (четыре пары) одну игру начинает игрок команды А, и одну игру — команда Б.
* Одна победа приносет команде 1 очко. Итого команда может получить от 0 до 8 очков.
* Ограничение 30 секунд на ход. Один судья следит за двумя парами, поэтому судейство здесь мягкое.

### Перерыв между этапами 

* Перерыв на обсуждение стратегии 10 минут.
* В течение первых 5 минут вольные стрелки могут передать письменно команде свои соображения по оптимальной стратегии

### Второй этап, командный

* Каждая команда выбирает капитана
* Команды играют на поле $1 \times 9$. 
* Играем две партии, в одной начинает команда А, в другой первый ход у команды Б
* Команда, набравшая больше баллов на первом этапе, получает право выбора,
будет ли она сначала ходить первой, а потом второй, или наоборот
* Ход делает только капитан
* Ограничение 30 секунд на ход. Здесь следим строго.
* Одна победа приносит команде 4 очка


## Правила игры

* Игра "Лужи на дороге" или "Домики-поддавки"
* Поле состоит из полоски $1 \times n$ клеточек
* Игроки по очереди соединяют две соседние ещё не соединённые вершины. 
* Соединяем по горизонтали или вертикали, НЕ по диагонали. 
* Тот, кто закончил соединять ребра вокруг клетки считает клетку своей лужей, и обязательно делает дополнительный ход. Для удобства занятую клетку можно пометить буквой игрока. 
* Тот, кто собрал к концу игры больше всего луж проиграл.

\newpage

## Выигрышная стратегия

* Все ребра делятся на граничные (целиком лежит на границе) и внутренние.
* Выигрышная стратегия есть у первого игрока
* Первый ход — выбираем любое внутреннее ребро кроме ребер, касающихся самого левого и самого правого квадратика.
* Если все внутреннии ребра заняты, то делаем любой ход граничным ребром, кроме замыкания лужи.
* Если не все внутренние ребра заняты, то смотрим на предыдущий ход второго игрока. 
* Если второй игрок только что выбрал внутренее ребро, то выбираем любое внутреннее ребро.
* Если второй игрок только что поставил граничное ребро, которое касается РОВНО ОДНОГО внутреннего ребра, то ставим второе внутреннее ребро, касающееся только что поставленного вторым игроком граничного ребра. При этом может оказаться, что мы захватили лужу. 
* Иначе выбираем любое внутреннее ребро.
* Подробнее про стратегию можно прочитать в Games of No Chance 4, 
Narrow misere Dots-and-Boxes. 
